//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hari_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evidencija
    {
        public int id { get; set; }
        public string vlasnik { get; set; }
        public string br_tablica { get; set; }
        public string tip_vozila { get; set; }
        public Nullable<System.DateTime> vreme_ulaza { get; set; }
        public Nullable<System.DateTime> vreme_izlaza { get; set; }
        public Nullable<int> vreme_provedeno { get; set; }
        public Nullable<double> naplaceno { get; set; }
    }
}
