//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hari_WPF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class haris_bazaEntities : DbContext
    {
        public haris_bazaEntities()
            : base("name=haris_bazaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Evidencija> Evidencijas { get; set; }
        public virtual DbSet<ParkingMesto> ParkingMestoes { get; set; }
        public virtual DbSet<Vozila> Vozilas { get; set; }
    }
}
