//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hari_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingMesto
    {
        public int brojMesta { get; set; }
        public Nullable<int> lokacija { get; set; }
        public Nullable<bool> statusZauzetosti { get; set; }
        public string vlasnik { get; set; }
        public string tip_vozila { get; set; }
        public string reg_broj { get; set; }
        public Nullable<System.DateTime> vreme_ulaska { get; set; }
    }
}
