//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hari_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vozila
    {
        public string kor_ime { get; set; }
        public string sifra { get; set; }
        public string vlasnik { get; set; }
        public string tip_vozila { get; set; }
        public string br_tablica { get; set; }
    }
}
